<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fb78edd6-a96b-470a-80bd-d8a5ce40e79b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Lafayette Convertible Dress&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/div[2]/div/div[2]/div/div/div[2]/div[2]/div[2]/ul/li[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Lafayette Convertible Dress&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd82e166-b5c4-4762-9605-a94a25421fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce.tealiumdemo.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/w/s/wsd013t.jpg</value>
      <webElementGuid>a3bc99d8-d28b-4780-a646-903d21407431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lafayette Convertible Dress</value>
      <webElementGuid>6c9c02f1-2f83-44e4-9a62-ce0b1d64490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;cms-index-index cms-home&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;main-container col1-layout&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;col-main&quot;]/div[@class=&quot;std&quot;]/div[@class=&quot;widget widget-new-products&quot;]/div[@class=&quot;widget-products&quot;]/ul[@class=&quot;products-grid products-grid--max-5-col-widget&quot;]/li[@class=&quot;item last&quot;]/a[@class=&quot;product-image&quot;]/img[1]</value>
      <webElementGuid>cd40fee4-f898-48d8-9373-99441c19750e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/div[2]/div/div[2]/div/div/div[2]/div[2]/div[2]/ul/li[4]/a/img</value>
      <webElementGuid>ce85f753-9e2d-4233-a688-8f41c8b12239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lafayette Convertible Dress']</value>
      <webElementGuid>1b2d1e4f-3795-49da-a2de-2f8ea964dec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a/img</value>
      <webElementGuid>c58472c0-9bae-469a-a004-de0e2e75a491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce.tealiumdemo.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/w/s/wsd013t.jpg' and @alt = 'Lafayette Convertible Dress']</value>
      <webElementGuid>b71dad04-39c5-4aa5-8e2c-0425e77f16ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
