<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>300e058f-c6c3-431b-ad6d-9ff66d75636d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.thumb-link > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product_addtocart_form']/div[2]/div[3]/ul/li[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#product_addtocart_form div >> internal:has-text=&quot;Lafayette Convertible Dress More Views&quot;i >> internal:role=link >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>09a043c1-6b11-47ef-b9eb-2d5cc1e74323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce.tealiumdemo.com/media/catalog/product/cache/1/thumbnail/75x/9df78eab33525d08d6e5fb8d27136e95/w/s/wsd013b_2.jpg</value>
      <webElementGuid>7aa0771b-75e4-4fde-83fa-a612bed4ddf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>8d0822f7-fc88-4245-b632-e11cd684cf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>93de55f5-dfd4-4ac3-8fa8-fe25fcd8b7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_addtocart_form&quot;)/div[@class=&quot;product-img-box&quot;]/div[@class=&quot;more-views&quot;]/ul[@class=&quot;product-image-thumbs&quot;]/li[3]/a[@class=&quot;thumb-link&quot;]/img[1]</value>
      <webElementGuid>86214f02-e996-4b5b-b098-96fab0d3dc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div[3]/ul/li[3]/a/img</value>
      <webElementGuid>48825803-a84b-4638-b2be-3ac2afcc2489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ecommerce.tealiumdemo.com/media/catalog/product/cache/1/thumbnail/75x/9df78eab33525d08d6e5fb8d27136e95/w/s/wsd013b_2.jpg')]</value>
      <webElementGuid>05fb7aa2-1521-4379-b597-e4213db44574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>f2efc263-307b-4c66-b75a-a85026c9e26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce.tealiumdemo.com/media/catalog/product/cache/1/thumbnail/75x/9df78eab33525d08d6e5fb8d27136e95/w/s/wsd013b_2.jpg']</value>
      <webElementGuid>4e0a2f8b-14b3-4fea-932e-a0ee07133242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
