<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reviews</name>
   <tag></tag>
   <elementGuidId>f1bbf814-e664-48d7-84dc-b51aa222e566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.last > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/div[2]/div/div[2]/div/div[2]/div[3]/div[2]/ul/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Reviews&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>33e64800-b989-4543-ac15-e2aaf0437e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reviews</value>
      <webElementGuid>c1a48705-4329-4cd1-862f-337a9de8d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;catalog-product-view catalog-product-view product-lafayette-convertible-dress&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;main-container col1-layout&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;col-main&quot;]/div[@class=&quot;product-view&quot;]/div[@class=&quot;product-collateral toggle-content tabs&quot;]/ul[@class=&quot;toggle-tabs&quot;]/li[@class=&quot;last&quot;]/span[1]</value>
      <webElementGuid>feac5a52-b029-4a41-88ad-118e6f997128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/div[2]/div/div[2]/div/div[2]/div[3]/div[2]/ul/li[3]/span</value>
      <webElementGuid>366068d1-7a0e-400c-a19d-8ac872f61f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Information'])[1]/following::span[1]</value>
      <webElementGuid>4a967821-5a43-4622-a4ba-7bb2b191ac8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[2]</value>
      <webElementGuid>5e9d38e8-3309-4090-8612-0322a9c392d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/preceding::span[1]</value>
      <webElementGuid>0043c0da-d213-422f-9be7-de944f70b2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::span[2]</value>
      <webElementGuid>3388700c-2521-4de6-8dfa-4f888e1cc066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviews']/parent::*</value>
      <webElementGuid>85e91c53-37f6-4b5b-83b9-de8fc647d740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>ae6af691-1c32-4ff4-a632-f5efbb16c217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reviews' or . = 'Reviews')]</value>
      <webElementGuid>5c75ce1f-3249-4485-bd1b-ee796fb6f4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
